package com.tx.txv_common.pojo;

import java.io.Serializable;
import java.util.Date;

public class TxPic implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_pic.pic_id
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    private String picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_pic.pic_location
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    private String picLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_pic.pic_video
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    private String picVideo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_pic.pic_desc
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    private String picDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_pic.pic_type
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    private String picType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_pic.status
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_pic.upload_time
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_pic.order
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    private String order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_pic.score
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    private String score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_pic.pic_name
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    private String picName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_pic.pic_data
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    private String picData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tx_pic
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_pic.pic_id
     *
     * @return the value of tx_pic.pic_id
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public String getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_pic.pic_id
     *
     * @param picId the value for tx_pic.pic_id
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public void setPicId(String picId) {
        this.picId = picId == null ? null : picId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_pic.pic_location
     *
     * @return the value of tx_pic.pic_location
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public String getPicLocation() {
        return picLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_pic.pic_location
     *
     * @param picLocation the value for tx_pic.pic_location
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public void setPicLocation(String picLocation) {
        this.picLocation = picLocation == null ? null : picLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_pic.pic_video
     *
     * @return the value of tx_pic.pic_video
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public String getPicVideo() {
        return picVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_pic.pic_video
     *
     * @param picVideo the value for tx_pic.pic_video
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public void setPicVideo(String picVideo) {
        this.picVideo = picVideo == null ? null : picVideo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_pic.pic_desc
     *
     * @return the value of tx_pic.pic_desc
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public String getPicDesc() {
        return picDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_pic.pic_desc
     *
     * @param picDesc the value for tx_pic.pic_desc
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public void setPicDesc(String picDesc) {
        this.picDesc = picDesc == null ? null : picDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_pic.pic_type
     *
     * @return the value of tx_pic.pic_type
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public String getPicType() {
        return picType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_pic.pic_type
     *
     * @param picType the value for tx_pic.pic_type
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public void setPicType(String picType) {
        this.picType = picType == null ? null : picType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_pic.status
     *
     * @return the value of tx_pic.status
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_pic.status
     *
     * @param status the value for tx_pic.status
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_pic.upload_time
     *
     * @return the value of tx_pic.upload_time
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_pic.upload_time
     *
     * @param uploadTime the value for tx_pic.upload_time
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_pic.order
     *
     * @return the value of tx_pic.order
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public String getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_pic.order
     *
     * @param order the value for tx_pic.order
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public void setOrder(String order) {
        this.order = order == null ? null : order.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_pic.score
     *
     * @return the value of tx_pic.score
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_pic.score
     *
     * @param score the value for tx_pic.score
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_pic.pic_name
     *
     * @return the value of tx_pic.pic_name
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_pic.pic_name
     *
     * @param picName the value for tx_pic.pic_name
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public void setPicName(String picName) {
        this.picName = picName == null ? null : picName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_pic.pic_data
     *
     * @return the value of tx_pic.pic_data
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public String getPicData() {
        return picData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_pic.pic_data
     *
     * @param picData the value for tx_pic.pic_data
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    public void setPicData(String picData) {
        this.picData = picData == null ? null : picData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_pic
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", picId=").append(picId);
        sb.append(", picLocation=").append(picLocation);
        sb.append(", picVideo=").append(picVideo);
        sb.append(", picDesc=").append(picDesc);
        sb.append(", picType=").append(picType);
        sb.append(", status=").append(status);
        sb.append(", uploadTime=").append(uploadTime);
        sb.append(", order=").append(order);
        sb.append(", score=").append(score);
        sb.append(", picName=").append(picName);
        sb.append(", picData=").append(picData);
        sb.append("]");
        return sb.toString();
    }
}