package com.tx.txv_common.pojo;

import java.io.Serializable;
import java.util.Date;

public class TxPoster implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_poster.POST_ID
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    private String postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_poster.POST_NAME
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    private String postName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_poster.POST_LOCATION
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    private String postLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_poster.POST_LABLE
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    private String postLable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_poster.POST_DESC
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    private String postDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_poster.POST_TYPE
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    private String postType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_poster.STATE
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_poster.UPLOAD_TIME
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_poster.UPLOAD_STAFF
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    private String uploadStaff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_poster.ORDER
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    private String order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_poster.SCORE
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    private String score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_poster.POST_DATA
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    private String postData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tx_poster
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_poster.POST_ID
     *
     * @return the value of tx_poster.POST_ID
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public String getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_poster.POST_ID
     *
     * @param postId the value for tx_poster.POST_ID
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public void setPostId(String postId) {
        this.postId = postId == null ? null : postId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_poster.POST_NAME
     *
     * @return the value of tx_poster.POST_NAME
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public String getPostName() {
        return postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_poster.POST_NAME
     *
     * @param postName the value for tx_poster.POST_NAME
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public void setPostName(String postName) {
        this.postName = postName == null ? null : postName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_poster.POST_LOCATION
     *
     * @return the value of tx_poster.POST_LOCATION
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public String getPostLocation() {
        return postLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_poster.POST_LOCATION
     *
     * @param postLocation the value for tx_poster.POST_LOCATION
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public void setPostLocation(String postLocation) {
        this.postLocation = postLocation == null ? null : postLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_poster.POST_LABLE
     *
     * @return the value of tx_poster.POST_LABLE
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public String getPostLable() {
        return postLable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_poster.POST_LABLE
     *
     * @param postLable the value for tx_poster.POST_LABLE
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public void setPostLable(String postLable) {
        this.postLable = postLable == null ? null : postLable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_poster.POST_DESC
     *
     * @return the value of tx_poster.POST_DESC
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public String getPostDesc() {
        return postDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_poster.POST_DESC
     *
     * @param postDesc the value for tx_poster.POST_DESC
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public void setPostDesc(String postDesc) {
        this.postDesc = postDesc == null ? null : postDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_poster.POST_TYPE
     *
     * @return the value of tx_poster.POST_TYPE
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public String getPostType() {
        return postType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_poster.POST_TYPE
     *
     * @param postType the value for tx_poster.POST_TYPE
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public void setPostType(String postType) {
        this.postType = postType == null ? null : postType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_poster.STATE
     *
     * @return the value of tx_poster.STATE
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_poster.STATE
     *
     * @param state the value for tx_poster.STATE
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_poster.UPLOAD_TIME
     *
     * @return the value of tx_poster.UPLOAD_TIME
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_poster.UPLOAD_TIME
     *
     * @param uploadTime the value for tx_poster.UPLOAD_TIME
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_poster.UPLOAD_STAFF
     *
     * @return the value of tx_poster.UPLOAD_STAFF
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public String getUploadStaff() {
        return uploadStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_poster.UPLOAD_STAFF
     *
     * @param uploadStaff the value for tx_poster.UPLOAD_STAFF
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public void setUploadStaff(String uploadStaff) {
        this.uploadStaff = uploadStaff == null ? null : uploadStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_poster.ORDER
     *
     * @return the value of tx_poster.ORDER
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public String getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_poster.ORDER
     *
     * @param order the value for tx_poster.ORDER
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public void setOrder(String order) {
        this.order = order == null ? null : order.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_poster.SCORE
     *
     * @return the value of tx_poster.SCORE
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_poster.SCORE
     *
     * @param score the value for tx_poster.SCORE
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_poster.POST_DATA
     *
     * @return the value of tx_poster.POST_DATA
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public String getPostData() {
        return postData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_poster.POST_DATA
     *
     * @param postData the value for tx_poster.POST_DATA
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    public void setPostData(String postData) {
        this.postData = postData == null ? null : postData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_poster
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", postId=").append(postId);
        sb.append(", postName=").append(postName);
        sb.append(", postLocation=").append(postLocation);
        sb.append(", postLable=").append(postLable);
        sb.append(", postDesc=").append(postDesc);
        sb.append(", postType=").append(postType);
        sb.append(", state=").append(state);
        sb.append(", uploadTime=").append(uploadTime);
        sb.append(", uploadStaff=").append(uploadStaff);
        sb.append(", order=").append(order);
        sb.append(", score=").append(score);
        sb.append(", postData=").append(postData);
        sb.append("]");
        return sb.toString();
    }
}