package com.tx.txv_provider.mapper;

import com.tx.txv_common.pojo.TxPic;
import com.tx.txv_common.pojo.TxPicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TxPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_pic
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    int countByExample(TxPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_pic
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    int deleteByExample(TxPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_pic
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    int deleteByPrimaryKey(String picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_pic
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    int insert(TxPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_pic
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    int insertSelective(TxPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_pic
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    List<TxPic> selectByExampleWithBLOBs(TxPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_pic
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    List<TxPic> selectByExample(TxPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_pic
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    TxPic selectByPrimaryKey(String picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_pic
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") TxPic record, @Param("example") TxPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_pic
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") TxPic record, @Param("example") TxPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_pic
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    int updateByExample(@Param("record") TxPic record, @Param("example") TxPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_pic
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    int updateByPrimaryKeySelective(TxPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_pic
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(TxPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_pic
     *
     * @mbggenerated Thu Dec 12 11:45:59 CST 2019
     */
    int updateByPrimaryKey(TxPic record);
}