package com.tx.txv_provider.mapper;

import com.tx.txv_common.pojo.TxPoster;
import com.tx.txv_common.pojo.TxPosterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TxPosterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_poster
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    int countByExample(TxPosterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_poster
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    int deleteByExample(TxPosterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_poster
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    int deleteByPrimaryKey(String postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_poster
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    int insert(TxPoster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_poster
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    int insertSelective(TxPoster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_poster
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    List<TxPoster> selectByExampleWithBLOBs(TxPosterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_poster
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    List<TxPoster> selectByExample(TxPosterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_poster
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    TxPoster selectByPrimaryKey(String postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_poster
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") TxPoster record, @Param("example") TxPosterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_poster
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") TxPoster record, @Param("example") TxPosterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_poster
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    int updateByExample(@Param("record") TxPoster record, @Param("example") TxPosterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_poster
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    int updateByPrimaryKeySelective(TxPoster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_poster
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(TxPoster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_poster
     *
     * @mbggenerated Thu Dec 19 16:36:05 CST 2019
     */
    int updateByPrimaryKey(TxPoster record);
}